name = "rx5808-analytics"
main = "analytics-worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
kv_namespaces = [
  { binding = "ANALYTICS", id = "272abf5bca9c4a78a4df3a5a99d5ac31" }
]
